### ISSUE TITLE
Curly brackets always used from \chapter even if square brackets present

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#51] opened 2018-12-24 04:25 UTC
The \chapter takes two parameters: in curly brackets (more common) and square brackets (less common).  If just curly brackets are used, that text is used for both the TOC and chapter header.  If curly and square are used, then the text in square brackets are used by LaTeX for the TOC and the text in curly brackets are used for the chapter header.  Tex4ebook appears to ignore the square brackets and use whatever's in the curly brackets for both TOC and chapter headers.  This is a problem for my current project because I have newlines in the chapter names where they appear at chapter headers, but this is ugly in the TOC.

In the context of this bug report, if only square brackets are used, it is legal for demons to fly out of the author's nose.

```
\documentclass{memoir}
\begin{document}
\tableofcontents*
\chapter[First Chapter]{First\\
Chapter}
\chapter[Second Chapter]{Second\\
Chapter}
\chapter[Third Chapter]{Third\\
Chapter}
\end{document}
```

**Comment by michal-h21** [comment] 2018-12-24 11:54
This seems to be caused by Memoir, it works with the Book class. Anyway, it can be fixed using the following configuration:

```
\Preamble{xhtml}
\Configure{writetoc}{\let\\\space}
\begin{document}
\EndPreamble
```

It is possible to redefine all macros that may cause issues in the TOC in the `\Configure{writetoc}` definition.

**Comment by DavidGriffith** [comment] 2018-12-25 06:54
Can this be fixed in tex4ebook to avoid surprising other authors down the line?

**Comment by michal-h21** [comment] 2018-12-25 16:02
Sure, I've reported this issue on [tex4ht issue tracker](https://puszcza.gnu.org.ua/bugs/index.php?406). I was not able to identify the source of the bug yet.

**Comment by michal-h21** [comment] 2019-01-06 23:44
The fix for this issue has been just pushed to TL.

**Closed** 2019-01-07 13:59 UTC
