### ISSUE TITLE
 Unbalanced Tag error in luaxml-mod-xml.lua when compiling epub3

### ISSUE THREAD

**Issue by JeanOlivier** [michal-h21/tex4ebook#62] opened 2019-10-22 17:48 UTC
I'm having issues compiling a document to epub3 and I don't know if I'm doing something wrong or if I stumbled upon a bug. I'm using a fresh install of TeXLive 2019, it was working with TeXLive 2017. 

Versions: 
> pdfTeX: 3.14159265-2.6-1.40.20 (TeX Live 2019)
> tex4ebook: v0.2c
> make4ht: v0.2g.

I'm compiling by running `tex4ebook -st -f epub3 -c epub3.cfg document`

The content of epub3.cfg is
```
\Preamble{xhtml}
    \Configure{graphics*}  
        {pdf}  
        {
            \Needs{"pdf2svg '\csname Gin@base\endcsname.pdf' '\csname Gin@base\endcsname_ebook.svg'"}%  
            \Picture[\csname a:GraphicsAlt\endcsname]{\csname Gin@base\endcsname_ebook.svg}%  
            \special{t4ht+@File: \csname Gin@base\endcsname_ebook.svg}
        }

\begin{document}
\EndPreamble
```

The error is `...ive/2019/texmf-dist/tex/luatex/luaxml/luaxml-mod-xml.lua:175: Unbalanced Tag (/meta) [char=508]`

The content of the `document-epub3` folder seems to have all the proper xhtml files generated, just not compiled into an epub.

I don't know Lua much but there's nothing obviously wrong with the quoted script line.

Any help is very appreciated.

**Comment by michal-h21** [comment] 2019-10-22 18:35
Could you also post a sample document here? I think it is caused by a mismatch between LuaXML and tex4ebook, which should be fixed in the development version of tex4ebook.

**Comment by JeanOlivier** [comment] 2019-10-22 18:45
Thank you for the fast answer.

Here's the complete code I'm using, sorry if it's not very clean: https://github.com/JeanOlivier/Template-Memoire

Compiling using `make epub3` generates my errors.

I had to uninstall TeXLive 2017 and install TeXLive 2019 because I tried to install the development version of tex4ebook and completely broken my TeX installation. Do you think the current development version would cooperate well with TeXLive 2019 installed today from tug.org?

**Comment by michal-h21** [comment] 2019-10-22 18:53
Ah, I am sorry to hear that :( 

The development version of `tex4ebook` seems to compile your document without validation errors. I've quickly looked over it and found some weird characters in the text. So there may be some issues probably with some Memoir commands that will need to be handled. 

I hope to release the stable version of `tex4ebook` soon. I would like to update the documentation and I am working on updating the code to use the latest features of `make4ht`. So it depends also on that. I've planned to upload it for some weeks, but I still keep finding new issues :(

**Comment by JeanOlivier** [comment] 2019-10-22 19:11
> Ah, I am sorry to hear that :(
Don't feel bad, your tool is very useful and well-made. TeX is a bit of a chaotic ecosystem so nobody can take every possible configurations into account.

I'll try and install the `devel` branch and see if it fixes my issue. Meanwhile I'll use epub2 with math as SVG. 

PS:
If I main point out a small issue without opening another Issue, `\caption*{some text}` in a figure environment does create a new figure number with "*" as the caption in the list of figures, whereas it shouldn't create a figure number nor appear in the LOF. Compile my example with `make epub2` to reproduce.

**Comment by michal-h21** [comment] 2019-10-22 19:27
No, please don't install the `devel` branch, it contains obsolete code. All development happens directly in `master`. It is not a good practice, I know.

I am sure there will be other Memoir issues. It would be best if you could post them to the tex4ht issue tracker. Or make a new issue here. Just to make it easier to keep track of these.

**Comment by JeanOlivier** [comment] 2019-10-22 19:38
Alright, I'll open new issues for the few problems I encounter.

Thanks again for the support!

**Comment by JeanOlivier** [comment] 2019-10-22 22:02
> I am sure there will be other Memoir issues.

Just to clarify, that's a template for a Memoir/Thesis, but I'm basing it on the book documentclass.

**Comment by michal-h21** [comment] 2022-06-09 15:54
I hope that this shouldn't happen anymore, so I can close this issue.

**Closed by michal-h21** 2022-06-09 15:54 UTC
