### ISSUE TITLE
No MOBI file being produced

### ISSUE THREAD

**Issue by gpontesss** [michal-h21/tex4ebook#81] opened 2021-09-22 13:20 UTC
When running with the `--format mobi` flag, it only produces epub files. A directory called `{filename}-mobi` is generated, but, again, only with a epub file. Are there any extra steps to convert it?

**Comment by michal-h21** [comment] 2021-09-23 13:40
`tex4ebook` uses `kindlegen`  command to convert Epub to MOBI. The problem is that Amazon doesn't provide it anymore. You can only download it from the Internet archive: https://www.reddit.com/r/kindle/comments/igveym/anybody_for_the_backup_zip_file_of_kindlegen/gdppak9/

I've added support for `ebook-convert` provided by Calibre to the development version of TeX4ebook, so you can try that, if you don't want to download `kindlegen`.

**Comment by gpontesss** [comment] 2021-09-28 22:25
I checked-out the `devel` branch and tried to run the `tex4ebook` script, but got the following output:

```sh
/usr/share/texmf-dist/scripts/make4ht/mkutils.lua:3: attempt to index a nil value (global 'logging')

```

When I run the script from the `master` branch, I get the following:

```sh
# Changes dir so that generated files don't clutter main folder.
[STATUS]  tex4ebook: Conversion started
[STATUS]  tex4ebook: Input file: /home/gpontesss/git/protocolo-42/main.tex
HTML Tidy for Linux version 5.7.45
sh: line 1: kindlegen: command not found
[ERROR]   mkutils: File main-mobi/main.mobi doesn't exist
cp: cannot stat 'main-mobi/main.mobi': No such file or directory
[STATUS]  tex4ebook: Conversion finished
/home/gpontesss/.config/texmf/tex/latex/tex4ebook/tex4ebook:204: attempt to call a nil value (field 'exit_status')
make: *** [Makefile:18: out/main.mobi] Error 1
```

I did install `kindlegen`, but its output didn't render the text. When I convert the generated epub file with Calibre, on its GUI, everything is rendered correctly. I'm also able to open the epub file using an ebook reader and it works as expected.

**Comment by michal-h21** [comment] 2021-09-29 08:05
The `devel` branch is not up-to-date, I do development in the `master` branch, so it fails because the code is too old. From the error messages in the `master` branch, I would guess that also `make4ht` is too old on your system. I probably should post updated version of `tex4ebook` to CTAN, so it will be available in TeX Live, and these errors should be gone. 

Regarding `kindlegen` is it available in the path? Can you run it from the command line? Could you also post output of `tex4ebook -a debug  -f mobi filename.tex`? I am curious why the updated `tex4ebook` cannot detect that it cannot be found.

**Comment by gpontesss** [comment] 2021-09-30 23:22
Oh, it makes sense now that the `devel` branch didn't work properly. About updating `make4ht`, I use arch, and updating a single package doesn't seem to be possible, for it conflicts with `texlive-core`. If you update CTAN I may be able to update it.

About `kindlegen`, it wasn't available for I had uninstalled it, to see if it would try to use `ebook-convert`. Apparently, it didn't try to use it. When `kindlegen` is available, the mobi file generated only contains the title page of the ebook, but none of the text.

**Comment by gpontesss** [comment] 2021-09-30 23:28
Ok, now it worked. It seems that `kindlegen` wasn't the problem, for just now I wasn't able to generated working epub files either. I am using `\input` command with shell escape to get the text I'm rendering, for I use some scripts to normalize some text and format it automatically. I checked out `tex4ebook`'s help command and it has a flag `--shell-escape`, which made me think that it would work. My file looks something like this:

```tex
\documentclass{scrreprt}

\usepackage{...}

\begin{document}

\maketitle{}
\input{|./script.sh}

\end{document}
```

Are there any caveats when using shell-escaped input?

**Comment by michal-h21** [comment] 2021-10-01 07:47
Yes, the `--shell-escape` option should do the trick. It works for me with this example:

```
\documentclass{scrreprt}


\begin{document}

\input{|./script.sh}

\end{document}
```

`script.sh`:

```
#!/usr/bin/bash
echo Hello world
```

**Comment by gpontesss** [comment] 2021-10-02 18:12
Ok, I think I found the problem, them. It seems that the `--output-dir` flag does not work well. (maybe I'm doing something wrong?) My Makefile looks something like this:

```Makefile
$(OUTDIR)/%.mobi: %.tex
    @cd $(dir $@); tex4ebook --format mobi $(abspath $<)
```

I did it because when I use the `--output-dir` flag, the files end up on my main folder, I wanted to avoid that. By doing the `cd` to the target folder, the script is no longer available at the path, so that's why it doesn't work. Weird that it fails silently.

I played with the `--output-dir`, and it does put the final file where it should, but the main folder still remains cluttered. Is it by design? Is there a away to avoid it? As far as generating mobi files, it seems to be working now.

**Comment by michal-h21** [comment] 2022-04-04 12:25
Sorry for the late reply, I somehow missed the additional question.

The `--output-dir` option just copies the generated Epub file. It doesn't try to remove the clutter. You can remove most of the clutter using `make4ht` in the `clean` mode:

      make4ht -m clean filename..tex

It doesn't compile the document, it just removes most of the generated temp files.

**Comment by gpontesss** [comment] 2022-04-04 21:57
cool, tks for the reply. I'll try it. as far as the issue goes, it seems to be solved.

**Comment by michal-h21** [comment] 2022-04-04 22:28
Great! I am closing it now.

**Closed** 2022-04-04 22:27 UTC
