### ISSUE TITLE
The element type "dc:creator" must be terminated by the matching end-tag "</dc:creator>".

### ISSUE THREAD

**Issue by rhaamo** [michal-h21/tex4ebook#25] opened 2016-08-16 11:05 UTC
I get this error with when running epubcheck:

```
ERROR(RSC-005): main.epub/OEBPS/content.opf(-1,-1): Error while parsing file 'The element type "dc:creator" must be terminated by the matching end-tag "</dc:creator>".'.
```

On build time I got some infos:

```
HTML Tidy for Linux released on 25 March 2009
Tidy ncx 0
line 12 column 40 - Error: unexpected </metadata> in <dc:creator>
line 99 column 9 - Error: unexpected </package> in <dc:creator>
Tidy opf 512
```

The content.opf creator part is:

```
<dc:creator> Dashie &#x003C;/dc:creator> 
<dc:creator>Fred, F4EED</dc:creator> 
```

I think the `\and` in my tex file isn't interpreted:

```
\author{
    Dashie
    \and
    Fred, F4EED
}
```

**Comment by michal-h21** [comment] 2016-08-22 13:38
Thanks for reporting, you are right, it was caused by `\and`, it inserted incorrect closing `</dc:creator>` tag. It is fixed in aba26dd9160996142369b843cfe16133e5f8f36f

**Comment by rhaamo** [comment] 2016-08-22 13:48
Thanks for the fix! I will look how to use this trunk instead of the tex4ebook from texlive.

**Comment by michal-h21** [comment] 2016-08-22 13:52
You can use `make install`, it should install it in your local TEXMF tree. But I think I should make new release soon, I only have to fix few other issues.

**Comment by FrankEular** [comment] 2019-01-21 18:46
It seems that \footnote is not supported in \author for tex4ebook? I met a similar compilation issue.

**Comment by michal-h21** [comment] 2019-01-22 12:13
@FrankEular  I've added new configuration to `tex4ebook`, so it is now possible to disable commands in `\author`:

```
\Preamble{xhtml}
\makeatletter
\Configure{@author}{\let\footnote\@gobble}
\makeatother
\begin{document}
\EndPreamble
```

It is available in the development version installed from Github.

**Comment by Iey4iej3** [comment] 2019-06-11 14:44
This issue could be closed.

**Comment by michal-h21** [comment] 2019-06-11 14:52
> This issue could be closed now.

yes, it seems so :)

**Closed by michal-h21** 2019-06-11 14:52 UTC
