### ISSUE TITLE
Fontspec support?

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#49] opened 2018-11-12 03:19 UTC
The README.md file states that fontspec is not supported and references details below to solve the problems.  However, I don't see those details.  Did they get accidentally deleted?

What needs to happen or be written for fontspec to be supported?

**Comment by michal-h21** [comment] 2018-11-12 09:05
That was outdated information, Fontspec is supported, but you must use either `-l` or `-x` options to use LuaLaTeX or XeLaTeX in the tex4ebook run.

**Comment by michal-h21** [comment] 2018-11-13 11:56
This document should work, of course only font styles and weight are used, not the fonts themselves. But the font inclusion [can be configured](https://tex.stackexchange.com/a/289562). 

Thanks for the report about missing -x option.

**Comment by DavidGriffith** [comment] 2018-11-13 15:38
Once I get this worked out, I'd like to add a few sample ebooks to this repo.

**Comment by michal-h21** [comment] 2018-11-13 19:54
Sure, that would be nice!

**Comment by michal-h21** [comment] 2018-11-20 11:57
The only description of `addfont4ht` and `include4ht` is in the answer you linked, I am afraid.

**Comment by DavidGriffith** [comment] 2018-11-21 02:42
I think I'll need a little help making progress.  Please take a look at https://github.com/DavidGriffith/ebook-test when you get a chance.

**Comment by michal-h21** [comment] 2018-11-21 15:09
Ah, I see. You don't need the htf files when you use Fontspec, the characters are included in a different way. I failed to install `garamondx` in a correct way, but I don't think it is useful as you declare fonts directly anyway. So I would just remove the `\usepackage{garamondx}` line.

You need to declare the Bordeaux fonts in the config file, called `myconfig.cfg`, for example. I would use this configuration:

```
\RequirePackage{include4ht}
\RequirePackage{addfont4ht}
\Preamble{xhtml}
% \CoverMetadata{cover.png}
% \AddCss{scale.css}
\Configure{textbf}{\NoFonts\HCode{<strong>}}{\HCode{</strong>}\EndNoFonts}
\Configure{textit}{\NoFonts\HCode{<em>}}{\HCode{</em>}\EndNoFonts}
\begin{document}
\NormalFont{Bordeaux}{BordeauxMedium-Regular.ttf}
\BoldFont{Bordeaux}{BordeauxLight-Italic.ttf}
\BoldItalicFont{Bordeaux}{BordeauxLight-Italic.ttf}
\ItalicFont{Bordeaux}{BordeauxLight-Italic.ttf}
\Configure{@HEAD}{
\HCode{<style type='text/css' >\Hnewline
body{font-family:rmfamily, "Bordeaux", sans-serif;
font-size:1.3em;
}\Hnewline
p img{display:inline;}
</style>}}
\EndPreamble

```

Of  course, you should use correct file names for the \ItalicFont and similar commands.  The configuration file can be requested using `-c` option for `tex4ebook`:

    tex4ebook -x -c config.cfg test.tex

**Comment by DavidGriffith** [comment] 2018-11-22 10:45
I got this to work, but I must be missing something about the grammar.  If I build an ```.epub```, the entire document is in Bordeaux and my declaration of the Animals font overwrites the normal font declaration.

**Comment by michal-h21** [comment] 2018-11-23 10:16
I've added some comments to [addfonts4ht](https://github.com/michal-h21/helpers4ht/blob/master/addfont4ht.sty), so it should be more clear how to use it, I hope.

The issue is that if you use the the same font declaration commands multiple times, they redefine the previous declarations. So the `\NormalFont{Animal}{Animals-Regular.ttf}` redefines normal font to be the Animals font. It is necessary to define new font family, using `\SetFontFamily` command.

There is also another issue, the `\animalfont` cannot be used as {\animalfont abc}, it is necessary to create command which will insert HTML tags that can be then styled using CSS. For example:

     \newcommand\animals[1]{\bgroup\animalsfont\Huge#1\egroup}
     ...
     \animals{a b c d e f g h i j k l m n o p q r s t u v w x y z}

And in the config file:

     \renewcommand\animals[1]{\HCode{<span class="animals">}#1\HCode{</span>}}

     \SetFontFamily{animal}
     \NormalFont{Animal}{Animals-Regular.ttf}
     \Css{ span.animals{font-family: animal, "Animal";font-size:2em;} }

**Comment by DavidGriffith** [comment] 2018-11-23 11:22
This inability to switch fonts by doing ```{\myfont abc}``` looks like a significant problem, mainly because it breaks how fonts are switched for building to PDF.  Suppose a work switches fonts after every paragraph.  Adding a ```\myfont```, then ```\foofont```, then ```\barfont``` is expected to work.

Rather than doing that ```\newcommand...``` stuff in the body of the document, how about doing it in Lua -- in the tex4ebook script or the ```.lua``` files?  I think I can see where and how a regex could do this automatically, but I need to get to sleep now.

**Comment by michal-h21** [comment] 2018-11-23 12:45
One solution I can think of is to redefine the `\animalsfont` in the config file to use some font which is not used at all in the document - for example small caps in small font. It will generate specific class, which can be then styled. For example, the following redefinition:

     \renewcommand\animalsfont{\small\scshape} 

will generate the following HTML:

     <span class="rm-lmcsc-10x-x-248">a b c d e f g h i j k l m n o p q r</span>

So it is necessary to style the `rm-lmcsc-10x-x-248` class to use the Animals font:

     \Css{span.rm-lmcsc-10x-x-248{font-family: Animal, "Animal";font-size:2em;}

**Comment by DavidGriffith** [comment] 2018-12-14 00:20
Is it possible to modify tex4ebook such that ```{\myfont abc}``` will work?  What sort of challenges are we looking at for this?

**Comment by michal-h21** [comment] 2018-12-17 12:31
@DavidGriffith only using the trick from my previous message. It is generally better to use `\myfont{abc}`, because it is possible to insert tags at the beginning and at the end of the command.

**Comment by michal-h21** [comment] 2018-12-19 08:46
I've figured out another possibility for fixing font switches issue. I am not sure how robust it is, but it seems to work for simple example:

```
\Preamble{xhtml}
\def\closeit{\HCode{</i>}}
\renewcommand\myfont{\HCode{<i>}\aftergroup\closeit}
\begin{document}
\EndPreamble
```
It uses the `\aftergroup` command to insert the closing tag. Try it with the following TeX file:
```
\documentclass{article}
\newcommand\myfont{\itshape}
\begin{document}

Hello {\myfont world, slightly longer \textbf{xxx}}
\end{document}
```

**Closed** 2021-01-24 10:06 UTC
