### ISSUE TITLE
Italics not closed

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#68] opened 2020-06-15 06:44 UTC
When running my epub through epubcheck, I get fatal errors like this:
````
FATAL(RSC-016): /home/dave/proj/ebooks/latex/foo/foo.epub/OEBPS/fooch2.html(34,3): Fatal Error while parsing file: The element type "i" must be terminated by the matching end-tag "</i>".
````
complaining that `<i>` elements are not being closed with a matching `</i>`.

**Comment by michal-h21** [comment] 2020-06-15 07:10
Can you please make a `mwe`? It seems like an error with some configuration. Don't you get some error towards the end of compilation when you run `tex4ebook -a debug foo.tex`?

**Comment by DavidGriffith** [comment] 2020-06-15 07:43
There's something a bit more general that not closing `<i>` elements.  While coming up with a `mwe`, each instance of `\textit{foo}` generated a complaint about `<p>` elements not being closed.  It happens only when the `fontspec` package is used.

````
\documentclass[12pt,extrafontsizes]{memoir}

\usepackage{lipsum}
\usepackage{fontspec}

\begin{document}
\parindent=7pt
\parskip=7pt

\title{\Huge\textbf{Latin Gibberish\normalsize}}
\author{Ralph}
\date{1440}

\maketitle

\begin{center}blah blah blah\end{center}

\chapter{Good Morning}
\lipsum[1]

\chapter{Good Afternoon}
\textit{``Now here is some italic text.''}

\lipsum[1]
\newpage

\chapter{Good Evening}

\textit{La La La La}
\lipsum[1]
\newpage
\end{document}
````

**Comment by michal-h21** [comment] 2020-06-15 11:03
I don't get these errors, they may be fixed by some recent TeX4ht updates. But I got some other errors, caused by `\title{}` with formatting instructions. I've updated TeX4ebook to fix these issues. Now I can get file without epubcheck errors.

**Comment by DavidGriffith** [comment] 2020-06-18 07:30
Now I get an error message of
````
...e/dave/texmf/tex/latex/tex4ebook/tex4ebook-exec_epub.lua:8: module 'luaxml-domobject' not found:
        no field package.preload['luaxml-domobject']
        [kpse lua searcher] file not found: 'luaxml-domobject'
        [kpse C searcher] file not found: 'luaxml-domobject'
make: *** [Makefile:24: epub] Error 1
````

**Comment by DavidGriffith** [comment] 2020-06-18 07:40
Now that the correct package is installed, I get even more error messages:
````
Validating using EPUB version 2.0.1 rules.
ERROR(RSC-005): /home/dave/proj/ebooks/latex/foo/test.epub/OEBPS/testch2.html(16,4): Error while parsing file: element "i" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")
ERROR(RSC-005): /home/dave/proj/ebooks/latex/foo/test.epub/OEBPS/testch2.html(17,34): Error while parsing file: element "p" not allowed here; expected the element end-tag, text or element "a", "abbr", "acronym", "applet", "b", "bdo", "big", "br", "cite", "code", "del", "dfn", "em", "i", "iframe", "img", "ins", "kbd", "map", "noscript", "ns:svg", "object", "q", "samp", "script", "small", "span", "strong", "sub", "sup", "tt" or "var" (with xmlns:ns="http://www.w3.org/2000/svg")
FATAL(RSC-016): /home/dave/proj/ebooks/latex/foo/test.epub/OEBPS/testch2.html(18,60): Fatal Error while parsing file: The element type "p" must be terminated by the matching end-tag "</p>".
ERROR(RSC-005): /home/dave/proj/ebooks/latex/foo/test.epub/OEBPS/testch2.html(-1,-1): Error while parsing file: The element type "p" must be terminated by the matching end-tag "</p>".
ERROR(RSC-005): /home/dave/proj/ebooks/latex/foo/test.epub/OEBPS/testch3.html(16,4): Error while parsing file: element "i" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")
ERROR(RSC-005): /home/dave/proj/ebooks/latex/foo/test.epub/OEBPS/testch3.html(17,34): Error while parsing file: element "p" not allowed here; expected the element end-tag, text or element "a", "abbr", "acronym", "applet", "b", "bdo", "big", "br", "cite", "code", "del", "dfn", "em", "i", "iframe", "img", "ins", "kbd", "map", "noscript", "ns:svg", "object", "q", "samp", "script", "small", "span", "strong", "sub", "sup", "tt" or "var" (with xmlns:ns="http://www.w3.org/2000/svg")
FATAL(RSC-016): /home/dave/proj/ebooks/latex/foo/test.epub/OEBPS/testch3.html(18,40): Fatal Error while parsing file: The element type "p" must be terminated by the matching end-tag "</p>".
ERROR(RSC-005): /home/dave/proj/ebooks/latex/foo/test.epub/OEBPS/testch3.html(-1,-1): Error while parsing file: The element type "p" must be terminated by the matching end-tag "</p>".

Check finished with errors
Messages: 2 fatals / 6 errors / 0 warnings / 0 infos

EPUBCheck completed
````

**Comment by michal-h21** [comment] 2020-06-18 08:48
It seems like a wrong configuration for italics is used on your system. It doesn't happen with vanilla TeX Live. You can try the following config file:

```
\Preamble{xhtml}
\Configure{textit}{\HCode{<i>}\NoFonts}{\EndNoFonts\HCode{</i>}}
\begin{document}
\EndPreamble

```

**Comment by DavidGriffith** [comment] 2020-06-20 06:13
It looks like I needed to add this line too:
````
\Configure{textsc}{\HCode{<span>}\NoFonts}{\EndNoFonts\HCode{</span>}}
````
The `<span>` tag was put around where smallcaps are used.  Somehow, this was rendered as just ordinary text, but see #69 for that.

**Comment by michal-h21** [comment] 2020-06-20 15:47
Yes, and also declaration for `\textbf`. This is the configuration used in TeX4ht sources:

```
\Configure{textit}{\HCode{<i>}\NoFonts}{\EndNoFonts\Tg</i>}
\Configure{textbf}{\HCode{<strong>}\NoFonts}{\EndNoFonts\Tg</strong>}
\Configure{textsc}{\HCode{<span class="small-caps">}\NoFonts}{\EndNoFonts\Tg</span>}
\Css{.small-caps{font-variant: small-caps;}}

```

**Closed** 2020-06-20 23:25 UTC
